## 10_FEATURE_SCALING
### DARSHAN M
### 230701061
### 22/10/2024

In [84]:
import numpy as np
import pandas as pd
df=pd.read_csv('2_datasetExample.csv')
df

SNO        RNO                    NAME  MARKS
0     1  230701001  AADITYA PARTHA SARATHY     40
1     2  230701002                AAKASH V     44
2     3  230701003            ABHILASH G R     44
3     4  230701004      ABHINAYA LAKSHMI S     48
4     5  230701005      ABHISHEK ROBIN S A     16
..  ...        ...                     ...    ...
65   66  230701504               KAAVIYA R     16
66   67  230701507          MAGESH VASAN M     38
67   68  230701510               SARANYA M     44
68   69  230701514              GANESHAN M     14
69   70  230701521               JABARAJ E      9

[70 rows x 4 columns]

In [86]:
df.head()

SNO        RNO                    NAME  MARKS
0    1  230701001  AADITYA PARTHA SARATHY     40
1    2  230701002                AAKASH V     44
2    3  230701003            ABHILASH G R     44
3    4  230701004      ABHINAYA LAKSHMI S     48
4    5  230701005      ABHISHEK ROBIN S A     16

In [94]:
df.MARKS.fillna(df.MARKS.mode()[0])
features=df.iloc[:,:-1].values
df

SNO        RNO                    NAME  MARKS
0     1  230701001  AADITYA PARTHA SARATHY     40
1     2  230701002                AAKASH V     44
2     3  230701003            ABHILASH G R     44
3     4  230701004      ABHINAYA LAKSHMI S     48
4     5  230701005      ABHISHEK ROBIN S A     16
..  ...        ...                     ...    ...
65   66  230701504               KAAVIYA R     16
66   67  230701507          MAGESH VASAN M     38
67   68  230701510               SARANYA M     44
68   69  230701514              GANESHAN M     14
69   70  230701521               JABARAJ E      9

[70 rows x 4 columns]

In [98]:
label=df.iloc[:,-1].values
from sklearn.impute import SimpleImputer
age=SimpleImputer(strategy="mean",missing_values=np.nan)
Salary=SimpleImputer(strategy="mean",missing_values=np.nan)
age.fit(features[:,[1]])


SimpleImputer()

In [106]:
SimpleImputer()

SimpleImputer()

In [114]:
features[:,[1]]=age.transform(features[:,[1]])
features

array([[1, 230701001.0, 'AADITYA PARTHA SARATHY'],
       [2, 230701002.0, 'AAKASH V'],
       [3, 230701003.0, 'ABHILASH G R'],
       [4, 230701004.0, 'ABHINAYA LAKSHMI S'],
       [5, 230701005.0, 'ABHISHEK ROBIN S A'],
       [6, 230701006.0, 'ABHISHEK S'],
       [7, 230701007.0, 'ABINAV S T'],
       [8, 230701008.0, 'ABIRAMI K'],
       [9, 230701009.0, 'ABISHEK I'],
       [10, 230701010.0, 'ABISHEK NATARAJAN'],
       [11, 230701011.0, 'ABOORVAN SHANMUGAPRIYA BABU'],
       [12, 230701012.0, 'ADHAVAN BALAJI N M'],
       [13, 230701013.0, 'ADITHYA J'],
       [14, 230701014.0, 'ADITHYAA SURESH'],
       [15, 230701015.0, 'AISHWARYA A'],
       [16, 230701016.0, 'AISHWARYA M'],
       [17, 230701017.0, 'AJAY SRINIVAS R'],
       [18, 230701018.0, 'AJEESH R R'],
       [19, 230701019.0, 'AKASH N'],
       [20, 230701020.0, 'AKILESH PRASAD I K'],
       [21, 230701021.0, 'AKSHAY KUMAR S'],
       [22, 230701022.0, 'AKSHAY VENKAT KRISHNA'],
       [23, 230701023.0, 'AKSHAYA BALAJI

In [116]:
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder(sparse_output=False)
Country=oh.fit_transform(features[:,[0]])
Country

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [118]:
final_set=np.concatenate((Country,features[:,[1,2]]),axis=1)
final_set

array([[1.0, 0.0, 0.0, ..., 0.0, 230701001.0, 'AADITYA PARTHA SARATHY'],
       [0.0, 1.0, 0.0, ..., 0.0, 230701002.0, 'AAKASH V'],
       [0.0, 0.0, 1.0, ..., 0.0, 230701003.0, 'ABHILASH G R'],
       ...,
       [0.0, 0.0, 0.0, ..., 0.0, 230701510.0, 'SARANYA M'],
       [0.0, 0.0, 0.0, ..., 0.0, 230701514.0, 'GANESHAN M'],
       [0.0, 0.0, 0.0, ..., 1.0, 230701521.0, 'JABARAJ E']], dtype=object)