## 1b_NUMPY
### DARSHAN M
### 230701061
### 06/08/2024

In [7]:
import numpy as np
array=np.random.randint(1,100,9)
array

array([38, 13, 41,  2, 67, 22, 22, 79, 62])

In [9]:
np.sqrt(array)

array([6.164414  , 3.60555128, 6.40312424, 1.41421356, 8.18535277,
       4.69041576, 4.69041576, 8.88819442, 7.87400787])

In [11]:
array.ndim //number of dimension

1

In [15]:
new_array=array.reshape(3,3) //changes 1d to 2d
new_array

array([[38, 13, 41],
       [ 2, 67, 22],
       [22, 79, 62]])

In [17]:
new_array.ndim

2

In [19]:
new_array.ravel() //flattens 2d into 1d

array([38, 13, 41,  2, 67, 22, 22, 79, 62])

In [25]:
newm=new_array.reshape(3,3)
newm

array([[38, 13, 41],
       [ 2, 67, 22],
       [22, 79, 62]])

In [27]:
newm[2,1:3]

array([79, 62])

In [29]:
newm[1:2,1:3]

array([[67, 22]])

In [31]:
new_array[0:3,0:0]

array([], shape=(3, 0), dtype=int32)

In [33]:
new_array[0:2,0:1]

array([[38],
       [ 2]])

In [35]:
new_array[0:3,0:1]

array([[38],
       [ 2],
       [22]])

In [37]:
new_array[1:3]

array([[ 2, 67, 22],
       [22, 79, 62]])